projectSource: 'pivotal'
projectId: null
remoteConfigUrl: null

isPartialRegex: '.*-wip$'
storiesRegex: '[\(\[](#[a-zA-Z0-9-]+,? ?)+[\)\]]'
storiesSource: title

github:
  url: http://www.github.com
  host: api.github.com
  apiPathPrefix: null
  owner: null
  repo: null

states:
  in-pr:
    moveTo: finished
    comment: '[[{{github.owner}}/{{github.repo}}#{{prNumber}}]]({{prUrl}}).'

  merged:
    moveTo: finished

  integrated:
    moveTo: delivered

  released:
    moveTo: delivered
