# Project management source.
# Required: Enum [pivotal | trello]
projectSource: null


# ID of the team's project
# Required: String
projectId: null


# A remote location to retrieve config rather than locally
# Optional: String
remoteConfigUrl: null


# Github configation
github:
  url: http://www.github.com
  host: api.github.com
  apiPathPrefix: null
  owner: null
  repo: null
  storiesSource: title


# Default Actions
actions:
  in-pr:
    state: finished
    comment: '[PR [{{github.repo}} #{{pullRequestId}}]]({{repoUrl}}/pull/{{pullRequestId}}) was opened.'

  merged: {}

  integrated:
    state: delivered

  released: {}
