# Future config
# remoteConfigUrl: null

# Installer
projectSource: null
projectId: null
storiesSource: null

# Non-Installer
isPartialRegex: '.*-wip$'
storiesRegex: '[\(\[](#[a-zA-Z0-9-]+,? ?)+[\)\]]'
storiesRegexIndex: 0

prInCommitRegexes:
  mergeCommit:
    test: 'Merge pull request #(\d+) from'
    index: 1
  squashCommit:
    test: '\(#(\d+)\)(\\n)?.*'
    index: 1

github:
  url: http://www.github.com
  apiHost: api.github.com
  apiPathPrefix: null
  owner: null
  project: null

states:
  in-pr:
    moveTo: finished
    comment: '[[{{github.owner}}/{{github.repo}}#{{prNumber}}]]({{prUrl}}).'

  merged:
    moveTo: finished

  integrated:
    moveTo: delivered

  released:
    moveTo: delivered
